spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: http://localhost:8080/realms/ForrajeriaIguazu
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id: gateway-forrajeria-service
            client-secret: 4C8c4gM0hIiGVQbWdmV77Pf5Cz5ROhSf
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: product-service
          uri: lb://forrajeria-service
          predicates:
            - Path=/productos/**
  application:
    name: gateway

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}




