server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forrajeriaazul
    username: root
    password: admin1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ForrajeriaIguazu
        registration:
          keycloak:
            client-id: keycloak-forrajeria-service
            #client-secret: CLocAsH2AjBSo0NOQd5FOER9tZg2Pnpe
            #redirect-uri: https://oauth.pstmn.io/v1/callback
  